vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    meals:
      uri_prefix: /images/meal
      upload_destination: "%kernel.project_dir%/public/images/meal"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
