parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\EntityListener\:
    resource: "../src/EntityListener"
    tags: ["doctrine.orm.entity_listener"]

  # Add more service definitions when explicit configuration is needed
  # Please note that last definitions always *replace* previous ones

  Symfony\Component\Security\Core\Security:
    public: true

  App\Security\UserProvider:
    arguments:
      $userRepository: '@App\Repository\UserRepository'

  Dompdf\Dompdf:
    arguments:
      $options: '@Dompdf\Options'

  Dompdf\Options: ~

  App\Command\:
    resource: "../src/Command"
    tags: ["console.command"]
